<?xml version="1.0" encoding="utf-8"?><Database Name="QuanLySanPham" Class="QuanLySanPhamDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.CTL" Member="CTLs">
    <Type Name="CTL">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CatalogCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CatalogName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="CTL_PD" Member="PDs" ThisKey="Id" OtherKey="CatalogID" Type="PD" />
    </Type>
  </Table>
  <Table Name="dbo.PD" Member="PDs">
    <Type Name="PD">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CatalogID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ProductCode" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="Picture" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="UnitPrice" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="CTL_PD" Member="CTL" ThisKey="CatalogID" OtherKey="Id" Type="CTL" IsForeignKey="true" />
    </Type>
  </Table>
</Database>